tasks:
  - init: pip3 install -r ./requirements.txt
  - command: pip3 uninstall jinja2
  - command: pip3 uninstall markupsafe
  - command: pip3 install jinja2
  - command: npm i -g heroku
image:
  file: .gitpod.Dockerfile
